'use strict';
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modal = $('#login-modal'), shell = $('#portal-shell'), nav = $('.nav nav');
$('#year').textContent = new Date().getFullYear();
$('.menu').addEventListener('click', () => $('.menu').setAttribute('aria-expanded', nav.classList.toggle('open')));
nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => {nav.classList.remove('open'); $('.menu').setAttribute('aria-expanded','false');}));
$('#contact-form').addEventListener('submit', e => {
  e.preventDefault(); const f = new FormData(e.currentTarget);
  location.href = 'mailto:sikhasahoo321@gmail.com?subject=' + encodeURIComponent('Stratwell enquiry: '+f.get('interest')) + '&body=' + encodeURIComponent('Hello Sikha,\n\nName: '+f.get('name')+'\nEmail: '+f.get('email')+'\nInterest: '+f.get('interest'));
  $('.form-message').textContent = 'Your email app will open with a draft. Send it there to contact Sikha.';
});
const roles = {
 candidate: {name:'Priya Sharma',email:'priya@demo.in',title:'Candidate portal',initials:'PS',caption:'Make your next career move count.'},
 client: {name:'Arjun Mehta',email:'arjun@demo.in',title:'Client portal',initials:'AM',caption:'Northstar Hospitals · Sample employer workspace'},
 recruiter: {name:'Meera Kapoor',email:'meera@demo.in',title:'Recruiter workspace',initials:'MK',caption:'Every candidate. Every next step. In view.'},
 admin: {name:'Sikha Sahoo',email:'admin@demo.in',title:'Admin control centre',initials:'SS',caption:'A clear view of the recruitment operation.'}
};
const key = 'stratwell-concept-demo-v3';
const seed = () => ({
 jobs:[{id:'j1',title:'ICU Nursing Lead',location:'Kolkata',pay:'₹8–12 LPA',type:'Permanent',brief:'Lead an ICU nursing team. B.Sc Nursing and critical care experience preferred.'},{id:'j2',title:'Head of Nursing',location:'Mumbai',pay:'₹14–18 LPA',type:'Permanent',brief:'Nursing leadership, clinical quality and team development.'},{id:'j3',title:'Senior Physiotherapist',location:'New Delhi',pay:'₹7–10 LPA',type:'Permanent',brief:'Support rehabilitation and individual treatment planning.'}],
 applications:[{id:'a1',job:'j1',name:'Priya Sharma',stage:'Shortlisted',note:'Six years in critical care nursing.'},{id:'a2',job:'j2',name:'Kavita Menon',stage:'Interview',note:'Nursing leadership experience.'}],
 profile:{name:'Priya Sharma',city:'Kolkata',speciality:'Critical care nursing',experience:'6',bio:'B.Sc Nursing, interested in ICU leadership opportunities.'},
 users:[{name:'CareBridge Clinic',email:'clinic@demo.in',role:'Client',status:'Pending'},{name:'Meera Kapoor',email:'meera@demo.in',role:'Recruiter',status:'Active'}],
 activity:['Sample recruitment workspace ready for presentation.']
});
let data = seed(), storageOK = true, role = 'candidate', view = 'overview', priorFocus;
try {const saved = JSON.parse(localStorage.getItem(key)); if(saved && Array.isArray(saved.jobs) && Array.isArray(saved.applications) && saved.profile && Array.isArray(saved.users) && Array.isArray(saved.activity)) data=saved;} catch {storageOK=false;}
function persist(message) {if(message)data.activity.unshift(message); data.activity=data.activity.slice(0,20); try{localStorage.setItem(key,JSON.stringify(data));}catch{storageOK=false;}}
const jobFor = id => data.jobs.find(j=>j.id===id) || {title:'Archived role',location:'India'};
const stages = ['Applied','Screening','Shortlisted','Interview','Offer','Placed'];
function openLogin(){priorFocus=document.activeElement; modal.classList.add('visible');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('.modal-close').focus();}
function closeLogin(){modal.classList.remove('visible');modal.setAttribute('aria-hidden','true');document.body.style.overflow=shell.classList.contains('active')?'hidden':'';priorFocus?.focus();}
document.querySelectorAll('[data-open-login]').forEach(b=>b.addEventListener('click',openLogin));
$('.modal-close').addEventListener('click',closeLogin);
modal.addEventListener('click',e=>{if(e.target===modal)closeLogin();});
modal.addEventListener('keydown',e=>{if(e.key==='Escape')closeLogin(); if(e.key==='Tab'){const list=[...modal.querySelectorAll('button,input')],first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
document.querySelectorAll('[data-login-role]').forEach(b=>b.addEventListener('click',()=>{$('#login-form').elements.email.value=roles[b.dataset.loginRole].email;$('#login-form').elements.password.value='Stratwell2026!';$('.login-error').textContent='';}));
$('#login-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,entry=Object.entries(roles).find(([,r])=>r.email===f.elements.email.value.trim().toLowerCase());if(!entry||f.elements.password.value!=='Stratwell2026!'){$('.login-error').textContent='Use one of the sample accounts and the demo password shown below.';return;} launch(entry[0]);});
document.querySelectorAll('[data-demo-role]').forEach(b=>b.addEventListener('click',()=>launch(b.dataset.demoRole)));
function launch(next){role=next;view='overview';closeLogin();shell.classList.add('active');document.body.style.overflow='hidden';$('#top').inert=true;$('.nav').inert=true;document.querySelector('footer').inert=true;draw();shell.focus();}
function leave(){shell.classList.remove('active');document.body.style.overflow='';$('#top').inert=false;$('.nav').inert=false;document.querySelector('footer').inert=false;$('.portal-link').focus();}
function btn(label,action,id='',light=false){return `<button class="action-btn ${light?'secondary':''}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;}
function metric(label,value){return `<div class="metric"><span>${label}</span><strong>${value}</strong></div>`;}
function navItems(){return [['overview','Overview'],['work',role==='candidate'?'My applications':role==='client'?'Vacancies & shortlists':role==='recruiter'?'Candidate pipeline':'People & access'],['action',role==='candidate'?'Find opportunities':role==='client'?'Post a vacancy':role==='recruiter'?'Interview coordination':'Add demo user'],['profile',role==='candidate'?'My profile':'Activity log']];}
function draw(){const d=roles[role];shell.innerHTML=`<div class="app"><aside class="app-side"><div class="app-brand"><i>S</i> STRATWELL CONNECT</div><span class="role-chip">${d.title}</span><nav aria-label="Portal navigation">${navItems().map(([v,n])=>`<button class="${view===v?'active':''}" data-view="${v}">${n}</button>`).join('')}</nav><div class="side-bottom"><small>Kolkata roots. India ambition.</small><button data-action="leave">← Back to website</button></div></aside><main class="app-main"><div class="app-top"><div><p class="app-eyebrow">STRATWELL CONNECT / ${esc(role)}</p><h1>${d.title}</h1><p>${d.caption}</p></div><div class="user-menu"><label class="switch-role">Explore as<select aria-label="Switch demo role">${Object.entries(roles).map(([k,r])=>`<option value="${k}" ${k===role?'selected':''}>${r.title}</option>`).join('')}</select></label><div class="avatar" title="${d.name}">${d.initials}</div></div></div><div class="mobile-nav">${navItems().map(([v,n])=>`<button class="${view===v?'active':''}" data-view="${v}">${n}</button>`).join('')}<button data-action="leave">Website</button></div><div class="demo-banner"><span><b>Concept demo</b> · Sample data. ${storageOK?'Changes stay in this browser.':'Storage unavailable; changes last for this visit.'} No messages or job applications are sent.</span>${btn('Reset demo','reset','',true)}</div><div id="app-view">${view==='overview'?overview():view==='work'?work():view==='action'?action():profile()}</div><div id="toast" role="status"></div></main></div>`;
 shell.querySelector('select[aria-label="Switch demo role"]').addEventListener('change',e=>launch(e.target.value));
 shell.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;draw();}));
 shell.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>dispatch(b.dataset.action,b.dataset.id)));
 shell.querySelector('form[data-kind]')?.addEventListener('submit',submit);
 shell.querySelector('#job-search')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();shell.querySelectorAll('[data-job-card]').forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(q));});
}
function summary(){const apps=role==='candidate'?data.applications.filter(a=>a.name===data.profile.name):data.applications;return `<div class="metric-grid">${metric(role==='candidate'?'My applications':'Open sample roles',role==='candidate'?apps.length:data.jobs.length)}${metric('In interview',apps.filter(a=>a.stage==='Interview').length)}${metric('Offers',apps.filter(a=>a.stage==='Offer').length)}${metric('Placements',apps.filter(a=>a.stage==='Placed').length)}</div>`;}
function overview(){return `<section class="welcome-strip"><div><p class="eyebrow">Your workspace</p><h2>Hello, ${esc(roles[role].name.split(' ')[0])}.</h2><p>${role==='candidate'?'Your next opportunity starts with a conversation.':'Keep people and progress at the centre of hiring.'}</p></div><div class="welcome-symbol" aria-hidden="true">✚</div></section>${summary()}<div class="panel-grid"><section class="panel"><div class="panel-heading"><h2>${role==='candidate'?'Your recruitment journey':'Hiring in focus'}</h2>${btn('Open workspace','work','',true)}</div>${applications(role==='candidate'?data.applications.filter(a=>a.name===data.profile.name):data.applications.slice(0,3),false)}</section><section class="panel"><p class="eyebrow teal">A connected workflow</p><h2>What happens next?</h2><ol class="next-steps"><li>Client shares a hiring brief</li><li>Candidate applies and recruiter reviews</li><li>Client interviews and confirms the offer</li><li>Recruiter records the joining</li></ol><p class="muted">Switch roles above to follow the same sample record through the journey.</p></section></div>`;}
function applications(items,interactive=true){if(!items.length)return '<p class="empty">No applications yet. Explore the sample roles to get started.</p>';return items.map(a=>{const j=jobFor(a.job);return `<article class="record"><div><h3>${esc(a.name)}</h3><p>${esc(j.title)} · ${esc(j.location)}</p><small>${esc(a.note)}</small>${a.interview?`<p class="interview-time">Interview: ${esc(a.interview.replace('T',' '))} IST</p>`:''}</div><div class="record-actions"><span class="status ${a.stage==='Interview'?'blue':''}">${esc(a.stage)}</span>${interactive&&role==='recruiter'&&a.stage!=='Placed'?btn('Move to '+stages[stages.indexOf(a.stage)+1],'advance',a.id):''}${interactive&&role==='client'&&a.stage==='Shortlisted'?btn('Request interview','interview',a.id):''}${interactive&&role==='client'&&a.stage==='Interview'?btn('Recommend offer','offer',a.id):''}</div></article>`;}).join('');}
function work(){if(role==='candidate')return `<section class="panel"><h2>My applications</h2>${applications(data.applications.filter(a=>a.name===data.profile.name))}</section>`;if(role==='client')return `<section class="panel"><h2>Vacancies & shortlists</h2>${data.jobs.map(j=>`<article class="record"><div><h3>${esc(j.title)}</h3><p>${esc(j.location)} · ${esc(j.type)} · ${esc(j.pay)}</p><small>${esc(j.brief)}</small></div><span class="status">${data.applications.filter(a=>a.job===j.id).length} applications</span></article>`).join('')}</section><section class="panel spaced"><h2>Review candidates</h2>${applications(data.applications.filter(a=>stages.indexOf(a.stage)>=2))}</section>`;if(role==='admin')return `<section class="panel"><h2>People & access</h2><p class="muted">Demo account records only. Approval does not grant access to a real service.</p>${data.users.map((u,i)=>`<article class="record"><div><h3>${esc(u.name)}</h3><p>${esc(u.email)} · ${esc(u.role)}</p></div><div class="record-actions"><span class="status">${esc(u.status)}</span>${u.status==='Pending'?btn('Approve sample account','approve',i):''}</div></article>`).join('')}</section>`;return `<section class="panel"><h2>Candidate pipeline</h2><div class="pipeline">${stages.map(stage=>`<div class="pipeline-col"><h3>${stage} <span>${data.applications.filter(a=>a.stage===stage).length}</span></h3>${data.applications.filter(a=>a.stage===stage).map(a=>`<article class="candidate-card"><b>${esc(a.name)}</b><small>${esc(jobFor(a.job).title)}</small>${stage!=='Placed'?btn('Next stage','advance',a.id):'<small>Joining recorded</small>'}</article>`).join('')}</div>`).join('')}</div></section>`;}
function input(label,name,value='',type='text'){return `<label>${label}<input name="${name}" type="${type}" required maxlength="180" value="${esc(value)}"></label>`;}
function form(kind,title,content,button){return `<section class="panel form-card"><h2>${title}</h2><form data-kind="${kind}">${content}<button class="action-btn" type="submit">${button}</button></form></section>`;}
function action(){if(role==='candidate')return `<section class="panel"><h2>Find opportunities</h2><label class="search-label">Search role or city<input id="job-search" type="search" placeholder="Try Kolkata or nursing"></label><div class="opportunity-grid">${data.jobs.map(j=>{const applied=data.applications.some(a=>a.job===j.id&&a.name===data.profile.name);return `<article class="opportunity" data-job-card><p class="eyebrow teal">${esc(j.location)} · ${esc(j.type)}</p><h3>${esc(j.title)}</h3><p>${esc(j.brief)}</p><strong>${esc(j.pay)}</strong>${applied?'<span class="status">Already applied</span>':btn('Apply in demo','apply',j.id)}</article>`;}).join('')}</div></section>`;if(role==='client')return form('vacancy','Post a sample vacancy',input('Job title','title')+input('Location','location','Kolkata')+input('Annual salary range','pay','₹6–10 LPA')+'<label>Employment type<select name="type"><option>Permanent</option><option>Contract</option><option>Locum</option></select></label><label>Hiring brief<textarea name="brief" required maxlength="600" placeholder="Speciality, experience and team requirements"></textarea></label>','Create sample vacancy');if(role==='recruiter'){const eligible=data.applications.filter(a=>a.stage==='Shortlisted'||a.stage==='Interview');if(!eligible.length)return '<section class="panel"><h2>Interview coordination</h2><p>Move a candidate to Shortlisted in the pipeline first.</p></section>';return form('schedule','Schedule a sample interview',`<label>Candidate<select name="application">${eligible.map(a=>`<option value="${a.id}">${esc(a.name)} / ${esc(jobFor(a.job).title)}</option>`).join('')}</select></label>`+input('Interview time (IST)','time','','datetime-local'),'Save interview');}return form('user','Add a sample user',input('Full name','name')+input('Demo email','email','','email')+'<label>Role<select name="role"><option>Recruiter</option><option>Client</option><option>Administrator</option></select></label>','Add demo record');}
function profile(){if(role!=='candidate')return `<section class="panel"><h2>Activity log</h2><p class="muted">Sample actions recorded in this browser.</p>${data.activity.map(t=>`<div class="activity">${esc(t)}</div>`).join('')}</section>`;const p=data.profile;return form('profile','My professional profile',input('Full name','name',p.name)+input('Preferred city','city',p.city)+input('Speciality','speciality',p.speciality)+`<label>Years of experience<input name="experience" type="number" min="0" max="60" required value="${esc(p.experience)}"></label><label>Career summary<textarea name="bio" maxlength="600" required>${esc(p.bio)}</textarea></label>`,'Save sample profile');}
function notify(message){draw();$('#toast').textContent=message;}
function dispatch(action,id){if(action==='leave')return leave();if(action==='work'){view='work';return draw();}if(action==='reset'){data=seed();persist();return notify('Sample workspace restored.');}if(action==='apply'){const j=data.jobs.find(j=>j.id===id);if(!j||data.applications.some(a=>a.job===id&&a.name===data.profile.name))return;data.applications.push({id:crypto.randomUUID(),job:id,name:data.profile.name,stage:'Applied',note:data.profile.bio});persist(data.profile.name+' applied for '+j.title+' in the demo.');return notify('Sample application saved. Switch to recruiter to review it.');}const a=data.applications.find(x=>x.id===id);if(action==='advance'&&a){const next=stages[stages.indexOf(a.stage)+1];if(next){a.stage=next;persist(a.name+' moved to '+next+'.');notify('Sample candidate moved to '+next+'.');}}if(action==='interview'&&a){a.stage='Interview';persist('Client requested an interview with '+a.name+'.');notify('Interview requested in the sample workflow.');}if(action==='offer'&&a){a.stage='Offer';persist('Client recommended an offer for '+a.name+'.');notify('Sample offer recommendation recorded.');}if(action==='approve'&&data.users[Number(id)]){data.users[Number(id)].status='Active';persist('Sample user approved: '+data.users[Number(id)].name);notify('Demo account marked active.');}}
function submit(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),kind=e.currentTarget.dataset.kind;for(const k in f)f[k]=f[k].trim();if(Object.values(f).some(v=>!v))return notify('Please complete all fields with sample details.');if(kind==='vacancy'){data.jobs.unshift({...f,id:crypto.randomUUID()});persist('New sample vacancy: '+f.title);view='work';notify('Sample vacancy created. It is now visible in the candidate portal.');}if(kind==='profile'){const old=data.profile.name;data.profile=f;data.applications.filter(a=>a.name===old).forEach(a=>a.name=f.name);persist('Candidate sample profile updated.');notify('Profile saved in this browser.');}if(kind==='schedule'){if(new Date(f.time+':00+05:30')<=new Date())return notify('Choose a future interview date and time.');const a=data.applications.find(a=>a.id===f.application);if(a){a.stage='Interview';a.interview=f.time;persist('Sample interview scheduled for '+a.name);view='work';notify('Sample interview saved. No invitation email was sent.');}}if(kind==='user'){if(data.users.some(u=>u.email.toLowerCase()===f.email.toLowerCase()))return notify('That sample email already exists.');data.users.push({...f,status:'Pending'});persist('Sample user added: '+f.name);view='work';notify('Demo user added for review. No invitation email was sent.');}}
